-- AlterTable
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "googleBusinessName" TEXT;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "currentWebsiteUrl" TEXT;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "inspirationWebsiteUrl" TEXT;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "businessHours" JSONB;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "focusServices" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "insuranceAccepted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "insuranceInfo" TEXT;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "financingInfo" TEXT;
ALTER TABLE "Site" ADD COLUMN IF NOT EXISTS "questionnaire" JSONB;
